### ISSUE TITLE
Error on the docs

### ISSUE THREAD

**Issue by ortegoncarlos** [nodify-at/gpt-pull-bot#1]
hi, you should change this on your docs: 
```
- name: Run GPT Review Action
      uses: nodify-at/gpt-review-action@main
```

```
 - name: Run GPT Review Action
    uses: nodify-at/gpt-pull-bot@1.0.1
```

its seems also there is asking for some input is not in the docs

throw new Error(`Input required and not supplied: ${name}`);

**Comment by nodify-at** [comment]
Thanks @ortegoncarlos! I've improved the README file now and released 1.0.3.
